#!/bin/bash

logpath=/var/log/boxsync
boxdavlocation=/mnt/box-dav
boxdest=/mnt/box

writelog() {
    while IFS= read -r line; do
        printf "%s boxsync: %s\n" "$(date +'%F %H:%M:%S')" "$line" >> $logpath
    done
}

# Mount Box location
/bin/mount -t davfs https://dav.box.com/dav $boxdavlocation
echo "Mount box-dav at $boxdavlocation" | writelog

# Begin rsync
# -u update
# -r recursive
# --progress show progress
# --delete delete files not in source
echo "Starting sync" | writelog
/bin/rsync -urh --progress --delete --exclude 'Podcasts' --exclude 'Playlists' $boxdavlocation/* $boxdest | writelog
/bin/rsync -rh --progress --delete --temp-dir=/tmp $boxdest/Playlists/ $boxdavlocation/Playlists | writelog

# Unmount Box location
echo "Unmount box-dav at $boxdavlocation" | writelog
/bin/umount $boxdavlocation